name: Auto Keka Attendance

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  attendance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install system dependencies for Pillow and Tesseract
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr libtesseract-dev libleptonica-dev \
            libjpeg-dev zlib1g-dev libpng-dev libfreetype6-dev pkg-config

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Attendance Script
        run: python app.py
