name: Auto Keka Attendance

# Run every minute + manual trigger
on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  attendance:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Step 3: Install Tesseract OCR binary
      - name: Install Tesseract OCR
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr

      # Step 4: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Run the Python script
      - name: Run Attendance Script
        run: python app.py

